# -*- coding: utf-8 -*-
"""Bot1colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvLnZfqRy20_JDmwDWQnzrzBDcbfmjpp
"""

import pandas as pd
import math
import Connect

df = pd.DataFrame([])
df['lows'] = []
df['highs'] = []
df['closes'] = []
#print(df)
''' cc = btcusd, solusd, ethusd '''  
print(Connect.GetStats('solusd','1m'))

"""Core-Satellite Approach
20% Actively managed 80% in passive
if Postive outlook: Trading exposure on BTC 100%
if Negative outlook: Bot says Price will go down then Trading exposure on BTC 60%
"""